# The URL the site will be built for

base_url = "https://nmarchiotto.dev"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

title = "Nicola Marchiotto"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# The default language; used in feeds.
default_language = "en"

[translations]
Biography = "Biography"
ContactMe = "Contact Me"
AboutMe = "About Me"
Interests = "Interests"
Experience = "Experience"
Education = "Education"
toc = "Table of Contents"
Published = "Published"
Abstract = "Abstract"
volume = "volume"
number = "number"
pages = "pages"


# Various slugification strategies, see below for details
# Defaults to everything being a slug
[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
avatar = "static/img/avatar2.jpg"   
favicon = "static/img/avatar2.jpg"

# Enter your email
email = "marchiotton@gmail.com"

contact_in_index = true

# Additional menu items
# `Name` is what it is displayed, `path` is the url
menu_items = [
   { path = "/", name = "About Me" },
]



# Translation related extra
language_codes = [ "en", "it" ]

[extra.it]
menu_items = [
   { path = "/it/", name = "About Me" },
]

# Your translations
[languages.it]
title = "Nicola Marchiotto"

[languages.it.translations]
Biography = "Biografia"
ContactMe = "Contattami"
AboutMe = "Su di me"
Interests = "Interessi"
Experience = "Esperienze"
Education = "Formazione"
toc = "Indice"
Published = "Pubblicato"
Abstract = "Abstract"
volume = "volume"
number = "numero"
pages = "pagine"