version: '3'

services:
  # FILEBROWSER
  filebrowser:
    container_name: filebrowser
    image:  hurlenko/filebrowser
    restart: unless-stopped
    ports:
      - 8081:8080
    volumes:
      - ~:/data
      - ~/dockers/filebrowser:/config
    networks:
      - medianetwork

  # JELLYFIN
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    volumes:
      - ~/dockers/jellyfin:/config
      - ~/media/shows:/data/tvshows
      - ~/media/movies:/data/movies
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    networks:
      - medianetwork
  
  #JACKETT
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - AUTO_UPDATE=true #optional
    volumes:
      - ~/dockers/jackett:/config
      - ~/media:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - medianetwork

  # PHOTOPRISM
  photoprism:
    container_name: photoprism
    image:  photoprism/photoprism:latest
    restart: unless-stopped
    ports:
      - 2342:2342
    volumes:
      - ~/dockers/photoprism:/photoprism/storage
      - ~/Pictures:/photoprism/originals
    environment:
      - PHOTOPRISM_UPLOAD_NSFW = "true"
      - PHOTOPRISM_ADMIN_PASSWORD = "insecure" 
    networks:
      - medianetwork
  
  # SONARR
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ~/dockers/sonar:/config
      - ~/media/shows:/tv #optional
      - ~/media:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - medianetwork
  
  # RADARR
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ~/dockers/radar:/config
      - ~/media/movies:/movies # optional 
      - ~/media:/downloads  # optional
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - medianetwork

  # QBITORRENT
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - WEBUI_PORT=8080
    volumes:
      - ~/dockers/qbittorrent:/config 
      - ~/media:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - medianetwork
  
  # HOMER to test with assets file
  # homer:
  #   image: b4bz/homer:latest
  #   container_name: homer
  #   ports:
  #     - 8082:8080
  #   volumes:
  #     - ./homer/assets/:/www/assets
  #   restart: unless-stopped
  #   networks:
  #     - medianetwork

# NETWORK DEFINITION
networks:
    medianetwork:
        name: medianetwork
        driver: bridge