[build]
publish = "public"
command = "npm run build && zola build --base-url https://nmarchiotto.dev/"

[build.environment]
ZOLA_VERSION = "0.16.1"

[context.deploy-preview]
publish = "public"
command = "npm run build && zola build --base-url https://nmarchiotto.dev/"

[[redirects]]
from = "https://main--nmarchiotto.netlify.app/*"
to = "https://nmarchiotto.dev/*"
